name: flutter_ticket
description: A Flutter ticket UI widget.
version: 1.0.0
homepage: https://github.com/lcsvcn/flutter-ticket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_clip_shadow: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
